config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do 
      put 'like' => 'posts#like'
    end
  end
  root 'static_pages#home'

  resources :users, except: [:new]

  get '/cadastro' , to: 'users#new'
  get '/friends' , to: 'users#showFriends'
  post '/friendships' , to: 'users#createFriendship' , as:'friendships'
  get '/lista-usuarios' , to: 'users#index'

  get '/login' , to: 'sessions#new'
  post'/login' , to: 'sessions#create'
  delete '/logout' , to: 'sessions#destroy'

  post '/comments' , to: 'posts#createComment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    has_one :user
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_voter
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    has_many :posts
    has_many :comments
    has_and_belongs_to_many :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def createComment
    @comment = Comment.new(comment_params)
    @comment.save
  end

  def like
    if !current_user.liked? @post 
      @post.liked_by current_user 
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :name, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :impede_logado, only: [:new]
    before_action :impede_nao_logado, only: [:destroy]

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            log_in(user)
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end

    private
    def impede_nao_logado
        if !logged_in?
            redirect_to login_path
        end
    end

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    before_action :impede_logado, only: [:home]
    
    def home
    end

    private
    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :impede_nao_logado, except: [:new, :create]
    before_action :impede_logado, only: [:new]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def index
        @users = User.all
    end


    def show
        @user = User.find(params[:id])
        @posts = Post.where(user: current_user)
        @frindship = Friendship.new
    end

    #friendships
    def showFriends
        @friends = Friendship.where(user: current_user)
        #friends_names = Array.new
        #friends.each do |friend|
        #    f_id = friend.friend_user_id
        #    f_name = User.find(f_id)
        #    friends_names.push(f_name)
        #end

        #@friends = friends_names
    end

    def createFriendship
        @friendship = Friendship.new(friendship_params)
        @friendship.save
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def impede_nao_logado
        if !logged_in?
            redirect_to root_path
        end
    end

    def friendship_params
        params.require(:friendship).permit(:user_id, :friend_user_id)
    end

    def reverse_friendship_params
        params.require(:friendship).permit(:friend_user_id, :user_id)
    end

    def impede_logado
        if logged_in?
            redirect_to current_user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            if @current_user.nil?
                @current_user = User.find_by(id: session[:user_id])
            else
                @current_user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rede Social</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !logged_in? %>
      <%= link_to 'Pagina Inicial', root_path %>
    <% end %>
    
    <% if logged_in? %>
      <%= link_to 'Pagina do Usuario', current_user %> |
      <%= link_to 'Log-out', logout_path, method: :delete %> |
      <%= link_to 'Lista de usuarios', '/lista-usuarios' %>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field(:post,:user_id, :value => current_user.id) %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user %></td>
        <td><%= post.name %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3> <%= @post.name %> </h3>

<p> <%= @post.content %> </p>

<p>From: <%= @post.user.name %> </p>



<% if @post.user == current_user %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%end%>

<%= link_to 'Back', posts_path %>
<br>
<% @post.comments.each do |comm| %>
    <%= comm.user.name %> comentou: <%= comm.content %>
    <br>
<%end%>
<br>

<% if logged_in? %>
    <%= link_to "Like", like_post_path(@post) , class:"like-btn", method: :put, remote: :true %>
    <span class="likes-count"><%= @post.get_upvotes.size %></span>
    <%= form_with(model: @comment) do |form| %>
        <div class="field">
            <%= form.label :content %>
            <%= form.text_field :content %>
        </div>

        <%= hidden_field(:comment,:user_id, :value => current_user.id) %>

        <%= hidden_field(:comment,:post_id, :value => @post.id) %>

        <div class="actions">
            <%= form.submit %>
        </div>
    <%end%>
<%end%>

app/views/static_pages/home.html.erb
<h1> Bem vindo ao site! </h1>

<%= link_to 'Cadastre-se agora', cadastro_path%>
<%= link_to 'Ja tem uma conta? faça Log-in', login_path%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <div class="field">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :email, "E-mail" %>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :password, "Senha" %>
        <%= form.password_field :password %>
    </div>

    <div class="field">
        <%= form.label :password_confirmation, "Confirmar Senha" %>
        <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions">
        <%= form.submit "Cadastrar" %>
    </div>

<% end %>

app/views/users/addFriend.html.erb
<%= @okok %>

app/views/users/index.html.erb

<h1>Lista de usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>E-mail</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Cadastre-se</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<br>

<%= @user.name %> 

<br>
<br>

<%= link_to 'Novo Post', new_post_path %>

<br>

<%= link_to 'Lista de amigos', '/friends' %>

<%= form_with(url: friendships_path, scope: :friendship) do |form| %>
    <%= hidden_field(:friendship,:user_id, :value => current_user.id) %>
    <%= hidden_field(:friendship,:friend_user_id, :value => @user.id) %>
    <div class="actions">
        <%= form.submit %>
    </div>
<%end%>

<% @posts.each do |post| %>
    <h3><%= post.name %></h3>
    <p><%= post.content %></p> 
<%end%>

app/views/users/showFriends.html.erb
<%= @friends.count() %>

app/views/users/userList.html.erb
<h1>Lista de todos usuarios: </h1>

<% @users.each do |user| %>
    <%= link_to user.name , user %>
    <br>
<% end %>